### ISSUE TITLE
Fine-Tuning with LoRA: LoRA image classification

### ISSUE THREAD

**Issue by asusevski** [shreydan/computer-vision-course#4]
Setup:
- model: `google/vit-base-patch16-224`: Same reason as Shrey shared, most well known model
- dataset: `oxford-iiit pets dataset`: Can compare easier with Shrey's results
- Will rely on HF PEFT library as I think this will provide the best learning experience

I will include showing how long it took to train on the setup and compare with Shrey's results with Transfer learning

Let me know your guys' thoughts!

**Comment by alanahmet** [comment]
Hi @asusevski I think there might be a mistake. Right now, I'm working on fine-tuning the LoRA chapter. You can see the distribution of work from this link: https://github.com/users/sezan92/projects/30/views/1

**Comment by asusevski** [comment]
Got it, removing this issue. Will take on KD instead.
